function deltaP = CBF8Robots_deltaP(in1)
%CBF8Robots_deltaP
%    deltaP = CBF8Robots_deltaP(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Jul-2022 15:51:20

p1x = in1(1,:);
p2x = in1(3,:);
p3x = in1(5,:);
p4x = in1(7,:);
p5x = in1(9,:);
p6x = in1(11,:);
p7x = in1(13,:);
p8x = in1(15,:);
p1y = in1(2,:);
p2y = in1(4,:);
p3y = in1(6,:);
p4y = in1(8,:);
p5y = in1(10,:);
p6y = in1(12,:);
p7y = in1(14,:);
p8y = in1(16,:);
t2 = -p3x;
t3 = -p4x;
t4 = -p5x;
t5 = -p6x;
t6 = -p7x;
t7 = -p8x;
t8 = -p3y;
t9 = -p4y;
t10 = -p5y;
t11 = -p6y;
t12 = -p7y;
t13 = -p8y;
mt1 = [sqrt(abs(p1x-p2x).^2+abs(p1y-p2y).^2);sqrt(abs(p1x+t2).^2+abs(p1y+t8).^2);sqrt(abs(p1x+t3).^2+abs(p1y+t9).^2);sqrt(abs(p1x+t4).^2+abs(p1y+t10).^2);sqrt(abs(p1x+t5).^2+abs(p1y+t11).^2);sqrt(abs(p1x+t6).^2+abs(p1y+t12).^2);sqrt(abs(p1x+t7).^2+abs(p1y+t13).^2);sqrt(abs(p2x+t2).^2+abs(p2y+t8).^2);sqrt(abs(p2x+t3).^2+abs(p2y+t9).^2);sqrt(abs(p2x+t4).^2+abs(p2y+t10).^2);sqrt(abs(p2x+t5).^2+abs(p2y+t11).^2)];
mt2 = [sqrt(abs(p2x+t6).^2+abs(p2y+t12).^2);sqrt(abs(p2x+t7).^2+abs(p2y+t13).^2);sqrt(abs(p3x+t3).^2+abs(p3y+t9).^2);sqrt(abs(p3x+t4).^2+abs(p3y+t10).^2);sqrt(abs(p3x+t5).^2+abs(p3y+t11).^2);sqrt(abs(p3x+t6).^2+abs(p3y+t12).^2);sqrt(abs(p3x+t7).^2+abs(p3y+t13).^2);sqrt(abs(p4x+t4).^2+abs(p4y+t10).^2);sqrt(abs(p4x+t5).^2+abs(p4y+t11).^2);sqrt(abs(p4x+t6).^2+abs(p4y+t12).^2);sqrt(abs(p4x+t7).^2+abs(p4y+t13).^2)];
mt3 = [sqrt(abs(p5x+t5).^2+abs(p5y+t11).^2);sqrt(abs(p5x+t6).^2+abs(p5y+t12).^2);sqrt(abs(p5x+t7).^2+abs(p5y+t13).^2);sqrt(abs(p6x+t6).^2+abs(p6y+t12).^2);sqrt(abs(p6x+t7).^2+abs(p6y+t13).^2);sqrt(abs(p7x+t7).^2+abs(p7y+t13).^2)];
deltaP = [mt1;mt2;mt3];
