function deltaP6 = CBF8Robots_deltaP6(in1)
%CBF8Robots_deltaP6
%    deltaP6 = CBF8Robots_deltaP6(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Jul-2022 15:51:29

p1x = in1(1,:);
p2x = in1(3,:);
p3x = in1(5,:);
p4x = in1(7,:);
p5x = in1(9,:);
p6x = in1(11,:);
p7x = in1(13,:);
p8x = in1(15,:);
p1y = in1(2,:);
p2y = in1(4,:);
p3y = in1(6,:);
p4y = in1(8,:);
p5y = in1(10,:);
p6y = in1(12,:);
p7y = in1(14,:);
p8y = in1(16,:);
t2 = -p6x;
t3 = -p6y;
deltaP6 = [sqrt(abs(p1x+t2).^2+abs(p1y+t3).^2);sqrt(abs(p2x+t2).^2+abs(p2y+t3).^2);sqrt(abs(p3x+t2).^2+abs(p3y+t3).^2);sqrt(abs(p4x+t2).^2+abs(p4y+t3).^2);sqrt(abs(p5x+t2).^2+abs(p5y+t3).^2);sqrt(abs(p6x-p7x).^2+abs(p6y-p7y).^2);sqrt(abs(p6x-p8x).^2+abs(p6y-p8y).^2)];
